-- create tables
create table tbl_draw (
    id                             number generated by default on null as identity 
                                   constraint tbl_draw_id_pk primary key,
    draw_date                      date,
    id_member_organizer            varchar2(4000 char),
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table tbl_member (
    id                             number generated by default on null as identity 
                                   constraint tbl_member_id_pk primary key,
    id_draw                        number
                                   constraint tbl_member_id_draw_fk
                                   references tbl_draw on delete cascade not null,
    name                           varchar2(255 char),
    email_address                  varchar2(255 char),
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index tbl_member_i1 on tbl_member (id_draw);

create table tbl_result (
    id                             number generated by default on null as identity 
                                   constraint tbl_result_id_pk primary key,
    id_draw                        number
                                   constraint tbl_result_id_draw_fk
                                   references tbl_draw on delete cascade not null,
    id_member_buyer                number
                                   constraint tbl_result_id_member_buyer_fk
                                   references tbl_member on delete cascade not null,
    id_member_getting              number
                                   constraint tbl_result_id_member_gettin_fk
                                   references tbl_member on delete cascade not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index tbl_result_i1 on tbl_result (id_draw);
create index tbl_result_i2 on tbl_result (id_member_buyer);
create index tbl_result_i3 on tbl_result (id_member_getting);

create table tbl_exclusions (
    id                             number generated by default on null as identity 
                                   constraint tbl_exclusions_id_pk primary key,
    id_draw                        number
                                   constraint tbl_exclusions_id_draw_fk
                                   references tbl_draw on delete cascade not null,
    id_member_buyer                number
                                   constraint tbl_exclusion_id_member_buy_fk
                                   references tbl_member on delete cascade not null,
    id_member_getting              number
                                   constraint tbl_exclusion_id_member_get_fk
                                   references tbl_member on delete cascade not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index tbl_exclusions_i1 on tbl_exclusions (id_draw);
create index tbl_exclusions_i2 on tbl_exclusions (id_member_buyer);
create index tbl_exclusions_i3 on tbl_exclusions (id_member_getting);


 
-- Generated by Quick SQL Wednesday November 17, 2021  20:35:10
 
/*
draw
    draw_date
    id_member_organizer
    
result
    id_draw /fk draw /nn
    id_member_buyer /fk member /nn
    id_member_getting /fk member /nn

exclusions
    id_draw /fk draw /nn
    id_member_buyer /fk member /nn
    id_member_getting /fk member /nn

member
    id_draw /fk draw /nn
    name
    email_address

# settings = { prefix: "tbl_", PK: "IDENTITY", semantics: "CHAR", auditCols: true, language: "EN", APEX: true }
*/
